;/**
; * @file test_lab3.cl
; * @author Generated by GitHub Copilot
; * @version 1.0
; * @date April 18, 2026
; * 
; *  Test Suite for lab3.cl Macros and Functions
; *  Copyright (C) 2026 Generated by GitHub Copilot
; *
; *  This program is free software: you can redistribute it and/or modify
; *  it under the terms of the GNU General Public License as published by
; *  the Free Software Foundation, either version 3 of the License, or
; *  (at your option) any later version.
; *
; *  This program is distributed in the hope that it will be useful,
; *  but WITHOUT ANY WARRANTY; without even the implied warranty of
; *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; *  GNU General Public License for more details.
; *
; *  You should have received a copy of the GNU General Public License
; *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
; */

#! /usr/bin/sbcl --script

; ******************************************************
; TEST SUITE FOR LAB3.CL MACROS AND FUNCTIONS
; THESE TESTS COVER MACRO EXPANSIONS AND GRADE VALIDATION
; ******************************************************

; Load lab3.cl macros and functions
(load "lab3.cl")
(format t "---~%")
(format t "lab3.cl macro and function loading complete~%")
(format t "---~%")

; Define sample grades for testing
(defvar PHYS101D '("PHYS" 101 4 "D"))
(defvar PHYS101Cm '("PHYS" 101 4 "C-"))

(defvar PHYS250F '("PHYS" 250 3 "F"))
(defvar PHYS250B '("PHYS" 250 3 "B"))
(defvar PHYS250Ap '("PHYS" 250 3 "A+"))

(defvar CHEM150C '("CHEM" 150 3 "C"))
(defvar CHEM150A '("CHEM" 150 3 "A"))
(defvar CHEM250B '("CHEM" 250 3 "B"))

(defvar notGrade 42)
(defvar missingField '("PHYS" 4 "C+"))
(defvar extraField '("PHYS" 100 4 "C+" 99))
(defvar invalidArea '(150 250 3 "C-"))
(defvar invalidNumber '("CHEM" "250" 3 "C-"))
(defvar invalidCredit '("CHEM" 250 "3" "C-"))
(defvar invalidGrade '("CHEM" 250 3 #\A))

(format t "~%Checking some macro expansions~%")
(format t "(grArea PHYS101D) expanded: ~A~%" (macroexpand-1 '(grArea PHYS101D)))
(format t "(grNum PHYS101D) expanded: ~A~%" (macroexpand-1 '(grNum PHYS101D)))
(format t "(grCred PHYS101D) expanded: ~A~%" (macroexpand-1 '(grCred PHYS101D)))
(format t "(grLetter PHYS101D) expanded: ~A~%" (macroexpand-1 '(grLetter PHYS101D)))
(format t "(letterRank PHYS101D) expanded: ~A~%" (macroexpand-1 '(letterRank PHYS101D)))
(format t "~%(okGradeForm PHYS101D) expanded: ~A~%" (macroexpand-1 '(okGradeForm PHYS101D)))
(format t "~%(courseMatch PHYS101D PHYS101Cm) expanded: ~A~%" (macroexpand-1 '(courseMatch PHYS101D PHYS101Cm)))
(format t "~%(reqPassed PHYS101D PHYS101Cm CHEM150C) expanded: ~A~%" (macroexpand-1 '(reqPassed PHYS101D PHYS101Cm CHEM150C)))
(format t "---~%")

(format t "~%Checking valid grades with okGradeForm, each should pass~%")
(format t "~A: result ~A~%" PHYS101D (okGradeForm PHYS101D))
(format t "~A: result ~A~%" PHYS101Cm (okGradeForm PHYS101Cm))
(format t "~A: result ~A~%" PHYS250F (okGradeForm PHYS250F))
(format t "~A: result ~A~%" PHYS250B (okGradeForm PHYS250B))
(format t "~A: result ~A~%" PHYS250Ap (okGradeForm PHYS250Ap))
(format t "~A: result ~A~%" CHEM150C (okGradeForm CHEM150C))
(format t "~A: result ~A~%" CHEM150A (okGradeForm CHEM150A))
(format t "---~%")

(format t "~%Checking invalid grades with okGradeForm, each should fail~%")
(format t "~A: result ~A~%" notGrade (okGradeForm notGrade))
(format t "~A: result ~A~%" missingField (okGradeForm missingField))
(format t "~A: result ~A~%" extraField (okGradeForm extraField))
(format t "~A: result ~A~%" invalidArea (okGradeForm invalidArea))
(format t "~A: result ~A~%" invalidNumber (okGradeForm invalidNumber))
(format t "~A: result ~A~%" invalidCredit (okGradeForm invalidCredit))
(format t "~A: result ~A~%" invalidGrade (okGradeForm invalidGrade))
(format t "---~%")

(format t "~%Checking course matches, each should pass~%")
(format t "Req and Act ~A (same var): result ~A~%" PHYS101Cm (courseMatch PHYS101Cm PHYS101Cm))
(format t "Req ~A, Act ~A (match): result ~A~%" CHEM150C CHEM150A (courseMatch CHEM150C CHEM150A))
(format t "Req ~A, Act ~A (match): result ~A~%" PHYS250Ap PHYS250B (courseMatch PHYS250Ap PHYS250B))
(format t "---~%")

(format t "~%Checking course matches, each should fail~%")
(format t "Req ~A (invalid), Act ~A: result ~A~%" notGrade PHYS101D (courseMatch notGrade PHYS101D))
(format t "Req ~A, Act ~A (invalid): result ~A~%" PHYS101D invalidNumber (courseMatch PHYS101D invalidNumber))
(format t "Req ~A, Act ~A (mismatch num): result ~A~%" PHYS101Cm PHYS250B (courseMatch PHYS101Cm PHYS250B))
(format t "Req ~A, Act ~A (mismatch area): result ~A~%" PHYS250B CHEM250B (courseMatch PHYS250B CHEM250B))
(format t "---~%")

(format t "~%Checking actual grades vs required, each should pass~%")
(format t "Req and Act ~A (exact match): result ~A~%" PHYS101Cm (meetsReq PHYS101Cm PHYS101Cm))
(format t "Req ~A, Act ~A (higher): result ~A~%" CHEM150C CHEM150A (meetsReq CHEM150C CHEM150A))
(format t "Req ~A (invalid), Act ~A: result ~A~%" invalidGrade PHYS101D (meetsReq invalidGrade PHYS101D))
(format t "---~%")

(format t "~%Checking actual grades vs required, each should fail~%")
(format t "Req ~A, Act ~A (mismatch): result ~A~%" PHYS101Cm PHYS250B (meetsReq PHYS101Cm PHYS250B))
(format t "Req ~A, Act ~A (mismatch): result ~A~%" PHYS250B CHEM250B (meetsReq PHYS250B CHEM250B))
(format t "Req ~A, Act ~A (too low): result ~A~%" PHYS250Ap PHYS250B (meetsReq PHYS250Ap PHYS250B))
(format t "Req ~A, Act ~A (invalid): result ~A~%" PHYS101D invalidCredit (meetsReq PHYS101D invalidCredit))
(format t "---~%")

(format t "~%Checking multiple actual grade args vs req using reqPassed, each should pass~%")
(format t "Req ~A, Act ~A (higher): result ~A~%" CHEM150C CHEM150A (reqPassed CHEM150C CHEM150A))
(format t "Req ~A Act ~A,~A,~A: result ~A~%" PHYS250B CHEM150A PHYS250F PHYS250Ap (reqPassed PHYS250B CHEM150A PHYS250F PHYS250Ap))
(format t "Req ~A (invalid), Act ~A, ~A: result ~A~%" extraField PHYS101D PHYS250F (reqPassed extraField PHYS101D PHYS250F))
(format t "Req ~A (invalid), no actual: result ~A~%" missingField (reqPassed missingField))
(format t "---~%")

(format t "~%Checking multiple actual grade args vs required, each should fail~%")
(format t "Req ~A, Act ~A, ~A, ~A (too low): result ~A~%" PHYS101Cm PHYS250B PHYS101D CHEM150C (reqPassed PHYS101Cm PHYS250B CHEM150C))
(format t "Req ~A, Act ~A (invalid): result ~A~%" PHYS101D invalidArea (reqPassed PHYS101D invalidArea))
(format t "Req ~A, no actuals: result ~A~%" CHEM150A (reqPassed CHEM150A))
(format t "---~%")
