;/**
; * @file test_lab2.cl
; * @author Generated by GitHub Copilot
; * @version 1.0
; * @date April 18, 2026
; * 
; *  Lab 2: Let-over-Lambda
; *  Test Suite for lab2.cl Functions
; *  Copyright (C) 2026 Generated by GitHub Copilot
; *
; *  This program is free software: you can redistribute it and/or modify
; *  it under the terms of the GNU General Public License as published by
; *  the Free Software Foundation, either version 3 of the License, or
; *  (at your option) any later version.
; *
; *  This program is distributed in the hope that it will be useful,
; *  but WITHOUT ANY WARRANTY; without even the implied warranty of
; *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; *  GNU General Public License for more details.
; *
; *  You should have received a copy of the GNU General Public License
; *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
; */

# !/usr/bin/sbcl --script
; THIS FILE TESTS THE CORE FUNCTIONALITY OF GRADE MANAGEMENT
; INCLUDING DISPATCHER CREATION, VALIDATION, AND CALCULATIONS
; ******************************************************

; Define valid departments for testing purposes
(defconstant TESTAREAS '("CHEM" "PHYS" "HIST" "ART"))

; Load the lab2.cl functions
(load "lab2.cl")
(format t "---~%")
(format t "lab2.cl functions loaded successfully~%")
(format t "---~%")

; Define department variables
; Valid ones
(defvar chem "CHEM")
(defvar phys "PHYS")
(defvar hist "HIST")
(defvar art "ART")
; Invalid one
(defvar invaliddept "INVALID")

; Define grade variables
; Valid grades
(defvar bminus "B-")
(defvar bplus "B+")
(defvar aminus "A-")
; Invalid grade
(defvar badgrade "Z")

; Define grade lists for testing
; Valid grades
(defvar validPhys1 '("PHYS" 101 4 "B"))
(defvar validPhys2 '("PHYS" 101 4 "B+"))
(defvar validChem '("CHEM" 150 3 "B-"))
(defvar validHist '("HIST" 200 3 "B"))
(defvar validArt (list art 250 4 bplus))
(defvar excellentArt (list art 250 4 aminus))
(defvar excellentPhys (list phys 101 4 aminus))
; Invalid grades
(defvar invalidShort (list "PHYS" 4 "B+"))
(defvar invalidLong (list phys 200 3 bminus bminus))
(defvar invalidDept (list invaliddept 130 3 bplus))
(defvar invalidCredits (list hist 230 10 bminus))
(defvar invalidGrade (list hist 230 3 badgrade))

; Build dispatchers from the grade lists
(format t "Creating grade dispatchers~%")

(defvar validPhys1Req (buildGrade validPhys1 t))
(defvar validPhys1Act (buildGrade validPhys1 nil))
(defvar validPhys2Req (buildGrade validPhys2 t))
(defvar validPhys2Act (buildGrade validPhys2 nil))
(defvar validChemReq (buildGrade validChem t))
(defvar validChemAct (buildGrade validChem nil))
(defvar validArtReq (buildGrade validArt t))
(defvar validArtAct (buildGrade validArt nil))
(defvar excellentArtReq (buildGrade excellentArt t))
(defvar excellentArtAct (buildGrade excellentArt nil))
(defvar excellentPhysReq (buildGrade excellentPhys t))
(defvar excellentPhysAct (buildGrade excellentPhys nil))
(defvar invalidShortReq (buildGrade invalidShort t))
(defvar invalidShortAct (buildGrade invalidShort nil))
(defvar invalidLongReq (buildGrade invalidLong t))
(defvar invalidLongAct (buildGrade invalidLong nil))
(defvar invalidDeptReq (buildGrade invalidDept t))
(defvar invalidDeptAct (buildGrade invalidDept nil))
(defvar invalidCreditsReq (buildGrade invalidCredits t))
(defvar invalidCreditsAct (buildGrade invalidCredits nil))
(defvar invalidGradeReq (buildGrade invalidGrade t))
(defvar invalidGradeAct (buildGrade invalidGrade nil))

(defvar sampleReqDisp (buildGrade validPhys1 t))
(defvar sampleActDisp (buildGrade validPhys2 nil))
(defvar badDisp (buildGrade invalidLong nil))
(defvar chemReqDisp (buildGrade validChem t))
(defvar chemActDisp (buildGrade validChem nil))
(format t "Dispatchers created~%")
(format t "---~%")

; Create lists of dispatchers for GPA and requirement checks
(defvar requirements (list sampleReqDisp chemReqDisp))
(defvar achievements (list sampleActDisp chemActDisp))
(defvar singleReq (list chemReqDisp))
(defvar singleAct (list chemActDisp))
(defvar mixedWithBad (list sampleActDisp badDisp chemActDisp))
(defvar allInvalidReq (list invalidShortReq invalidLongReq invalidDeptReq invalidCreditsReq invalidGradeReq))
(defvar allInvalidAct (list invalidShortAct invalidLongAct invalidDeptAct invalidCreditsAct invalidGradeAct))
(defvar allValidReq (list validPhys1Req validPhys2Req validChemReq validArtReq))
(defvar allValidAct (list validPhys1Act validPhys2Act validChemAct validArtAct))
(defvar highReq (list excellentPhysReq excellentArtReq))
(defvar highAct (list excellentPhysAct excellentArtAct))
(defvar mixedReq (list excellentPhysReq excellentArtReq invalidDeptReq))
(defvar mixedAct (list excellentPhysAct excellentArtAct invalidDeptAct))

; Test getter functions on dispatchers
(format t "Testing getter functions on various dispatchers~%")
(format t "isReq on sampleReqDisp:~%")
   (format t "   ... ~A~%" (funcall sampleReqDisp 'isReq))
(format t "isReq on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'isReq))
(format t "getArea on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getArea))
(format t "getCnum on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getCnum))
(format t "getCred on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getCred))
(format t "getLetG on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getLetG))
(format t "getGPA on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getGPA))
(format t "getWGPA on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'getWGPA))
(format t "isValid on sampleActDisp:~%")
   (format t "   ... ~A~%" (funcall sampleActDisp 'isValid))
(format t "getAsList on sampleActDisp, based on ~A:~%" validPhys2)
   (format t "   ... ~A~%" (funcall sampleActDisp 'getAsList))
(format t "isValid on badDisp:~%")
   (format t "   ... ~A~%" (funcall badDisp 'isValid))
(format t "---~%")

(format t "isReq on invalidDeptAct:~%")
   (format t "   ... ~A~%" (funcall invalidDeptAct 'isReq))
(format t "getWGPA on excellentArtAct:~%")
   (format t "   ... ~A~%" (funcall excellentArtAct 'getWGPA))

; Test meetsReq functionality
(format t "Testing meetsReq on dispatchers~%")
(format t "sampleReqDisp meets validPhys1 (should be true)~%")
    (format t "   ... ~A~%" (funcall sampleReqDisp 'meetsReq validPhys1))
(format t "sampleActDisp meets validPhys1 (should be true)~%")
    (format t "   ... ~A~%" (funcall sampleActDisp 'meetsReq validPhys1))
(format t "chemActDisp meets validPhys1 (should be false)~%")
    (format t "   ... ~A~%" (funcall chemActDisp 'meetsReq validPhys1))
(format t "---~%")
(format t "excellentArtAct meets excellentArt (should be true)~%")
    (format t "   ... ~A~%" (funcall excellentArtAct 'meetsReq excellentArt))
(format t "excellentArtReq meets validChem (should be false)~%")
    (format t "   ... ~A~%" (funcall excellentArtReq 'meetsReq validChem))
(format t "invalidDeptReq meets validChem (should be false)~%")
    (format t "   ... ~A~%" (funcall invalidDeptReq 'meetsReq validChem))

; Test meetsAllReqs on lists
(format t "Testing meetsAllReqs on dispatcher lists~%")
(format t "(meetsAllReqs requirements achievements) should pass~%")
(format t "   ... result: ~A~%" (meetsAllReqs requirements achievements))

(format t "(meetsAllReqs requirements singleAct) should fail~%")
(format t "   ... result: ~A~%" (meetsAllReqs requirements singleAct))
(format t "---~%")
(format t "(meetsAllReqs allValidReq allValidAct) should pass~%")
(format t "   ... result: ~A~%" (meetsAllReqs allValidReq allValidAct))
(format t "(meetsAllReqs highReq allValidAct) should fail~%")
(format t "   ... result: ~A~%" (meetsAllReqs highReq allValidAct))
(format t "(meetsAllReqs allInvalidReq allValidAct) should pass~%")
(format t "   ... result: ~A~%" (meetsAllReqs allInvalidReq allValidAct))
(format t "(meetsAllReqs mixedReq allValidAct) should fail~%")
(format t "   ... result: ~A~%" (meetsAllReqs mixedReq allValidAct))
(format t "(meetsAllReqs mixedReq mixedAct) should pass~%")
(format t "   ... result: ~A~%" (meetsAllReqs mixedReq mixedAct))

; Test gpaCalc
(format t "Testing gpaCalc on dispatcher lists~%")
(format t "gpaCalc on achievements, expected around 2.05~%")
   (format t "   ... result: ~A~%" (gpaCalc achievements))
(format t "gpaCalc on mixedWithBad, expected around 2.05~%")
   (format t "   ... result: ~A~%" (gpaCalc mixedWithBad))

(format t "gpaCalc on highReq, expected around 3.67~%")
   (format t "   ... result: ~A~%" (gpaCalc highReq))
(format t "gpaCalc on allInvalidReq, expected 0~%")
   (format t "   ... result: ~A~%" (gpaCalc allInvalidReq))
(format t "---~%")